{% set version = "2.16.0.0" %}

package:
  name: vcversioner
  version: {{ version }}

source:
  fn: vcversioner-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/c5/cc/33162c0a7b28a4d8c83da07bc2b12cee58c120b4a9e8bba31c41c8d35a16/vcversioner-{{ version }}.tar.gz
  md5: aab6ef5e0cf8614a1b1140ed5b7f107d

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - vcversioner

about:
  home: https://github.com/habnabit/vcversioner
  license: ISC
  summary: 'Take version numbers from version control.'

extra:
  recipe-maintainers:
    - anguslees
    - minrk
    - ocefpaf
