travis:
  secure:
    BINSTAR_TOKEN: qLgU/JfWDZnx/Y6hHqc+s0eJU6ezW+NOjjGKJpzPhoqUFhFFT/N2V52l+tmqd7qcNKNyDUrz2c0B/j26VaDFMQKfA/rXpQ8REljwMPNb8wOAcORJdSiaQQCjGEtBwUelJOCrmbxao+uomc+CRwGnXyN0t20N+JaFnJrGhttLcaO9TuPfXv6pVr2LtMuugnr3TR1slP3W7gYzYsoqikvbzaOiyhrTmYu2MrG3dLlBZVgRRHLlDLW2ZqaepaEPTfmoylWClUHQnvRcLd0WGZ0Lh5ivsnGlS48/dhso544lHPHuEllk51wlcf2oHxAMwTWJOfdwTT3uIkBli5Q35ThDq8FQCDSUihewQhCXAPHGJ5Cgjjr9T2PfdV7/Kf9HcRKBJv+LLPlI8IyZNSxkJs01aC//Wfad4Gjxqh4DANnxsWN26o7rJ5CnFaXPhnUQ2qLOcmov4O9pwr4Zkg7DEvM/4D+auUNa0SVyqHAv8a4tSPTj2iEyJWNMJmFEsd6VQx4MV04tFIsPT6ZqocpEb/JBUwGuwBiUrTN3B2O1zT+MVfWRWN2HLW+jl1JbFVeWmxfcQnm0GLZVC1ZCj36UAQLRCYCILE/swGgUo35BJ39DUdzkl6xigUTcv0DUL1pjeJwNtB11RaYJ4WP8ABY6jC+jXk33D7dnhs2c0QJt6bKa6X4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
